### ISSUE TITLE
SortTuppleArray

### ISSUE THREAD

**Issue by aorgish** [artem1833/NET-Tasks#3]
https://github.com/artem1833/NET-Tasks/blob/master/02-Generics/Generics/Generics.cs#L116-L149

Это copy-paste стиль. От него надо избавляться. 
В основном подход такой: для начала смотрим, что постоянно в таких строчках, а что меняется. Изменяемые части выносим в переменные и оставляем только один экземпляр постоянной части (с новыми переменными)

**Comment by artem1833** [comment]
Не могу понять как в данном случае уйти от этого, смог только сократить код, перенеся логику в другое место.

            Array.Sort(array, (x, y) =>
            {
                switch (sortedColumn)
                {
                    case 0:
                        if (ascending)
                        {
                            return x.Item1.CompareTo(y.Item1);
                        }
                        return y.Item1.CompareTo(x.Item1);
                    case 1:
                        if (ascending)
                        {
                            return x.Item2.CompareTo(y.Item2);
                        }
                        return y.Item2.CompareTo(x.Item2);
                    case 2:
                        if (ascending)
                        {
                            return x.Item3.CompareTo(y.Item3);
                        }
                        return y.Item3.CompareTo(x.Item3);
                    default:
                        throw new IndexOutOfRangeException();
                }
            });
